{% set version = "0.7.0" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: ee935ba52f1d4a514cc3baa743db0377af732952faf800f20ffd8071fa2107c2

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

  run:
    - python >=3.5
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A set functions and classes for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - camerontstark
