{% set version = "0.5.2" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: b187abbc5ee921823d83b696740469ce5df47d42205507812dd39e8471da27a1

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.9.0
    - pandas >=0.14.0
    - pytz
    - six

  run:
    - python
    - numpy >=1.9.0
    - pandas >=0.14.0
    - pytz
    - six

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  summary: 'A set functions and classes for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
