{% set name = "pvlib" %}
{% set version = "0.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: cef36cdd932a6a7bf2dd7c992b0004b1a08d315ee8043b273d192ad57902e85a

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - numpy >=1.19.3
        - pandas >=1.3.0
        - pip
        - python >=3.9
        - pytz
        - requests
        - scipy >=1.6.0
        - h5py
        - numba >=0.17.0
        - ephem
        - statsmodels
        - importlib-metadata
        - setuptools_scm >=6.2
        - setuptools >=70.1
      run:
        - numpy >=1.19.3
        - pandas >=1.3.0
        - pip
        - python >=3.9
        - pytz
        - requests
        - scipy >=1.6.0
        - h5py
        - numba >=0.17.0
        - ephem
        - statsmodels
        - importlib-metadata
    test:
      imports:
        - pvlib

  - name: pvlib-python
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - mikofski
    - kandersolar
