{% set version = "0.7.2" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: 40708492ed0a41e900d36933b9b9ab7b575c72ebf3eee81293c626e301aa7ea1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

  run:
    - python >=3.5
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - camerontstark
