{% set name = "pvlib" %}
{% set version = "0.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: d02dbda515f2be54efd2e32839527c0f82e9f99028b460565facad068ac8574a

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - numpy >=1.19.3
        - pandas >=1.3.0
        - pip
        - python >=3.9
        - pytz
        - requests
        - scipy >=1.6.0
        - h5py
        - numba >=0.17.0
        - ephem
        - statsmodels
        - importlib-metadata
        - setuptools_scm >=6.2
        - setuptools >=61
      run:
        - numpy >=1.19.3
        - pandas >=1.3.0
        - pip
        - python >=3.9
        - pytz
        - requests
        - scipy >=1.6.0
        - h5py
        - numba >=0.17.0
        - ephem
        - statsmodels
        - importlib-metadata
    test:
      imports:
        - pvlib

  - name: pvlib-python
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - mikofski
    - kandersolar
