{% set version = "0.9.1" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: ead96f47898befd7728ab0b61b9747231008e151ef78a26d5e41d0b6a95a3a9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - numpy >=1.16.0
    - pandas >=0.22.0
    - pip
    - python >=3.6
    - pytz
    - requests
    - scipy >=1.2.0
    - h5py
    - numba
    - ephem
    - netcdf4
    - cftime >=1.1.1
    - statsmodels
    - dataclasses
  run:
    - numpy >=1.16.0
    - pandas >=0.22.0
    - pip
    - python >=3.6
    - pytz
    - requests
    - scipy >=1.2.0
    - h5py
    - numba
    - ephem
    - netcdf4
    - cftime >=1.1.1
    - statsmodels
    - dataclasses

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - mikofski
    - kanderso-nrel
