{% set version = "0.8.1" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: 3e735627c625e7e3777dec44ce5343600e0a96bce2077ad2563be5ac5f223352

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - numpy >=1.12.0
    - pandas >=0.22.0
    - pip
    - python >=3.6
    - pytz
    - requests
    - scipy >=1.2.0
    - pytables
    - numba
    - ephem
    - netcdf4
    - cftime >=1.1.1
    - statsmodels
  run:
    - numpy >=1.12.0
    - pandas >=0.22.0
    - pip
    - python >=3.6
    - pytz
    - requests
    - scipy >=1.2.0
    - pytables
    - numba
    - ephem
    - netcdf4
    - cftime >=1.1.1
    - statsmodels

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - mikofski
    - kanderso-nrel
