{% set version = "0.6.3" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: c9d8297951f94e26cd824d67a3362d38e6fdd32950542e13cca7316deb7ddb0e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.10.1
    - pandas >=0.14.0
    - pytz
    - six
    - scipy
    - pytables
    - numba
    - ephem

  run:
    - python
    - numpy >=1.10.1
    - pandas >=0.14.0
    - pytz
    - six
    - scipy
    - pytables
    - numba
    - ephem

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  summary: 'A set functions and classes for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
