{% set name = "pvlib" %}
{% set version = "0.10.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: 024a1b523d73a633323612e7f315a1709cf06d1fd43ff0821901f66a4068b2d9

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - numpy >=1.16.0
        - pandas >=0.25.0
        - pip
        - python >=3.7
        - pytz
        - requests
        - scipy >=1.5.0
        - h5py
        - numba
        - ephem
        - statsmodels
        - importlib-metadata
        - setuptools_scm >=6.2
      run:
        - numpy >=1.16.0
        - pandas >=0.25.0
        - pip
        - python >=3.7
        - pytz
        - requests
        - scipy >=1.5.0
        - h5py
        - numba
        - ephem
        - statsmodels
        - importlib-metadata
    test:
      imports:
        - pvlib

  - name: pvlib-python
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set functions and classes for simulating the performance of photovoltaic energy systems.

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - mikofski
    - kandersolar
