{% set version = "0.4.5" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  md5: 8067236c7b363f5a98917f7919300514

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.0
    - pandas >=0.14.0
    - pytz
    - six

  run:
    - python
    - numpy >=1.9.0
    - pandas >=0.14.0
    - pytz
    - six

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  summary: 'A set functions and classes for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
