{% set version = "0.7.1" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  sha256: 6db0321e652b4e470b368d74681419196ecc8dda69b48b4c1e95ec36d7b41ccf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

  run:
    - python >=3.5
    - numpy >=1.12.0
    - pandas >=0.18.1
    - pytz
    - requests
    - six
    - scipy
    - pytables
    - numba
    - ephem

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A set functions and classes for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
    - cwhanse
    - camerontstark
