travis:
  secure:
    BINSTAR_TOKEN: HxfTtNgtUF5N8FmxHhHkVzXIQ1oUTzzHwFFD5+9WxK0yVyLfxZ0douzfxHmphCaUzFPkvFKXGUVwADDLLo4UUHTD4UHzhaXETXnQUAP6A2f3Q1fvRrTjILemY9DeClkDr1Xnmrp6ySOVGHsBG2eOXpHRP3vLqxCy2ESsPFJufnxU0oD2qXBTeR42IBmc910D8k26Dcaz3W3wxWlGS9TpbJtRADxfP1l89NrNji0n8SExi30EBwdgpdGeMi5pr5DeFuZ66MpRXFeA883HPrq9UZOUPOG+xv9SgeRVP1gix7+hdmmarTNa1UVVT8FCb6BBsjOhK9Qe4vWEF6LiXixFLCGowiWhK69Wy37J9MJ7lpShpZrkY/icx6IZe+eC4gMyc0AWHyj/c6tuwK9m+wexGFnc3Zp9aAiZg0LUwVERLfbrHrPnkFKFSmVg3/5ywE8Fy7MPw3DFF4EAOaqSaUwo7idUkOTSoJamgH5r5MI/+gusKaMOYOiOmK3/lBar55kWu5Je82E7iuU916NsrKt5tuUr+FsVBgal2qGulORVniWJgbY6gYqh64m02rIsJ8Wx2wSgx07ly7ljwGTzwZGbmg6IZElQ9zKgSMU3RVZXeppFhI4Lwjijm4qQKk7efNV0CUuWlYUW7qKa9ROo1Ma/52JJP/zztG3P3sboJcxAdVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
